export const employeeData = [
    {
      avartar: "/profile.png",
      staffName: "Olorunfemi Ayobami",
      email: "Olorunfemiayobami26@gmailcom",
      department: "Content Creation",
      position: "Team Member",
      phone_no: "+2348106867506",
      city: "Ibadan, Nigeria",
      action: "Details",
    },
    {
      avartar: "/profile.png",
      staffName: "Olorunfemi Ayobami",
      email: "Olorunfemiayobami26@gmailcom",
      department: "Content Creation",
      position: "Team Member",
      phone_no: "+2348106867506",
      city: "Ibadan, Nigeria",
      action: "Details",
    },
    {
      avartar: "/profile.png",
      staffName: "Olorunfemi Ayobami",
      email: "Olorunfemiayobami26@gmailcom",
      department: "Content Creation",
      position: "Team Member",
      phone_no: "+2348106867506",
      city: "Ibadan, Nigeria",
      action: "Details",
    },
    {
      avartar: "/profile.png",
      staffName: "Olorunfemi Ayobami",
      email: "Olorunfemiayobami26@gmailcom",
      department: "Content Creation",
      position: "Team Member",
      phone_no: "+2348106867506",
      city: "Ibadan, Nigeria",
      action: "Details",
    },
    {
      avartar: "/profile.png",
      staffName: "Olorunfemi Ayobami",
      email: "Olorunfemiayobami26@gmailcom",
      department: "Content Creation",
      position: "Team Member",
      phone_no: "+2348106867506",
      city: "Ibadan, Nigeria",
      action: "Details",
    },
    {
      avartar: "/profile.png",
      staffName: "Olorunfemi Ayobami",
      email: "Olorunfemiayobami26@gmailcom",
      department: "Content Creation",
      position: "Team Member",
      phone_no: "+2348106867506",
      city: "Ibadan, Nigeria",
      action: "Details",
    },
  ];