import axios from "axios";

export const employeeData = [
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
  {
    avartar: "/profile.png",
    staffName: "Olorunfemi Ayobami",
    email: "Olorunfemiayobami26@gmailcom",
    department: "Content Creation",
    position: "Team Member",
    phone_no: "+2348106867506",
    city: "Ibadan, Nigeria",
    action: "Details",
  },
];

export const taskData = [
  {
    date: "22nd, October, 2023",
    taskDesc:
      "Conduct outreach to potential customers via phone, email, and social media.",
    staff: "Olorunfemi Ayobami",
    phoneNo: +2348106867506,
    action: "Details",
  },
  {
    date: "22nd, October, 2023",
    taskDesc: "Qualify leads and determine their needs.",
    staff: "Bisi Olaitan",
    phoneNo: +2348106867506,
    action: "Details",
  },
  {
    date: "22nd, October, 2023",
    taskDesc: "Qualify leads and determine their needs.",
    staff: "Adaobi Nwamaka",
    phoneNo: +2348106867506,
    action: "Details",
  },
  {
    date: "22nd, October, 2023",
    taskDesc: "Qualify leads and determine their needs.",
    staff: "Bisi Olaitan",
    phoneNo: +2348106867506,
    action: "Details",
  },
  {
    date: "22nd, October, 2023",
    taskDesc: "Qualify leads and determine their needs.",
    staff: "Bisi Olaitan",
    phoneNo: +2348106867506,
    action: "Details",
  },
];

export const pricing = [
  {
    pack: "Starter Pack",
    popularity: "",
    description:
      "Perfect for small businesses and startups looking for an affordable solution.",
    specification: [
      { list: "5 Staff", available: true },
      { list: "Task Delegation to Staff", available: true },
      { list: "Basic End-of-Day Reports", available: true },
      { list: "Query Handling", available: false },
      { list: "In-Depth Analytics and Insights", available: false },
      { list: "HR-Staff Communication Tools", available: true },
      { list: "Email Support", available: true },
    ],
    price: 12.0,
  },
  {
    pack: "Creative Pack",
    popularity: "Most Popular Plan!",
    description:
      "Perfect for middle scale companies, with a growing workforce.",
    specification: [
      { list: "5 Staff", available: true },
      { list: "Task Delegation to Staff", available: true },
      { list: "Basic End-of-Day Reports", available: true },
      { list: "Query Handling", available: true },
      { list: "In-Depth Analytics and Insights", available: false },
      { list: "HR-Staff Communication Tools", available: true },
      { list: "Email Support", available: true },
    ],
    price: 30.0,
  },
  {
    pack: "Business Pack",
    popularity: "",
    description:
      "Perfect for Large companies, seeking adequate  management of workforce",
    specification: [
      { list: "5 Staff", available: true },
      { list: "Task Delegation to Staff", available: true },
      { list: "Basic End-of-Day Reports", available: true },
      { list: "Query Handling", available: true },
      { list: "In-Depth Analytics and Insights", available: true },
      { list: "HR-Staff Communication Tools", available: true },
      { list: "Email Support", available: true },
    ],
    price: 60.0,
  },
];

const url = "https://kosmoshr.pythonanywhere.com/api/v1/";
export const TESTAPI = () => {
  axios
    .get(url)
    .then((resp) => {
      console.log(resp.data);
      alert("good");
      console.log(resp.data);
      return resp.data;
    })
    .catch((err) => {
      alert("err");
      console.log(err);
      return err;
    });
};

export const employeeurl = 'https://kosmoshr.pythonanywhere.com/api/v1/employees/'
const baseUrl = "https://backend.getlinked.ai";
// export const employeeurl = `${baseUrl}/hackathon/categories-list`;
